# Generated by Django 4.2.2 on 2023-06-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_rename_product_cartitem_product"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-date_added"]},
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.CharField(default=None, max_length=8000),
        ),
    ]
