# Generated by Django 4.2.2 on 2023-06-15 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_delivery"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="order",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.order",
            ),
        ),
    ]
