# Generated by Django 4.2 on 2023-07-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_product_sold_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_sold",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
