# Generated by Django 4.2 on 2023-07-07 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0011_about_alter_category_options_alter_product_options_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="About",
        ),
    ]
