# Generated by Django 4.2 on 2023-07-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0012_delete_about"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("details", models.TextField()),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_editted", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
